// Generated by CoffeeScript 1.4.0
var get, set;

get = Em.get;

set = Em.set;

module.exports = function(options) {
  return Em.Mixin.create({
    tagName: 'ul',
    classNames: ['sortable'],
    didInsertElement: function() {
      var controller, el, that;
      require('jquery-ui');
      that = this;
      controller = get(that, 'controller');
      options.update = function(event, ui) {
        var rows;
        rows = that.$('> li').toArray();
        return rows.forEach(function(row, position) {
          var item, view;
          view = Em.View.views[$(row).attr('id')];
          item = get(view, 'content');
          controller = get(that, 'controller');
          return controller.updateItem(item, position + 1);
        });
      };
      el = this.$();
      return el.sortable(options);
    }
  });
};
