// Generated by CoffeeScript 1.6.2
require('ember');

module.exports = function(options) {
  return Em.Mixin.create({
    tagName: 'ul',
    classNames: ['component-sortable'],
    didInsertElement: function() {
      var controller, el, that;

      require('jquery-ui');
      that = this;
      controller = that.get('controller');
      options.update = function(event, ui) {
        var rows;

        rows = that.$('> li').toArray();
        return rows.forEach(function(row, position) {
          var item, view;

          view = Em.View.views[$(row).attr('id')];
          item = view.get('content');
          return item.set('__position__', position + 1);
        });
      };
      el = this.$();
      return el.sortable(options);
    }
  });
};
